// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/jflex/lexer.jflex

package Analizadores;
import java_cup.runtime.*;

/* Directivas */

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\0\1\10\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\12\22\1\23"+
    "\1\24\1\25\1\26\1\27\2\0\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\31\1\36\1\37\2\31\1\40"+
    "\1\41\1\42\1\43\2\31\1\44\1\45\1\46\1\31"+
    "\1\47\1\50\3\31\1\51\1\0\1\52\1\0\1\53"+
    "\1\0\1\30\1\31\1\32\1\33\1\34\1\35\1\31"+
    "\1\36\1\37\2\31\1\40\1\41\1\42\1\43\2\31"+
    "\1\44\1\45\1\46\1\31\1\47\1\50\3\31\1\0"+
    "\1\54\10\0\1\3\252\0\2\55\115\0\1\56\u01a8\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\1\1\20\10\1\1\21\1\22\2\1"+
    "\1\23\1\0\1\24\1\25\1\26\1\27\2\0\1\30"+
    "\1\31\1\32\1\33\1\34\1\0\2\34\1\0\2\34"+
    "\1\35\5\34\1\36\1\35\3\0\1\37\1\34\2\40"+
    "\3\34\1\41\1\42\2\34\1\0\1\34\2\0\1\41"+
    "\1\0\1\43\4\34\1\0\1\44\1\34\1\0\1\34"+
    "\2\0\1\43\4\0\2\34\1\45\1\34\1\0\2\46"+
    "\2\47\1\0\1\43\1\50\1\51\2\52\2\0\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\274\0\57\0\353"+
    "\0\57\0\57\0\57\0\u011a\0\57\0\u0149\0\57\0\u0178"+
    "\0\u01a7\0\57\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1"+
    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\57\0\57\0\u03db"+
    "\0\u040a\0\57\0\274\0\274\0\57\0\57\0\57\0\u0439"+
    "\0\u0468\0\57\0\57\0\57\0\57\0\u0263\0\u0263\0\u0497"+
    "\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0263\0\u0582\0\u05b1\0\u05e0"+
    "\0\u060f\0\u063e\0\57\0\57\0\u066d\0\u069c\0\u06cb\0\u0468"+
    "\0\u06fa\0\u0263\0\57\0\u0729\0\u0758\0\u0787\0\u0263\0\u0263"+
    "\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\57\0\u08d0"+
    "\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0263\0\u0a19"+
    "\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u08ff"+
    "\0\u0b04\0\u0b91\0\u0bc0\0\u0263\0\u0bef\0\u0c1e\0\u0263\0\57"+
    "\0\u0263\0\57\0\u0c4d\0\u0c7c\0\u0263\0\u0263\0\u0263\0\57"+
    "\0\u0c7c\0\u0cab\0\57";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\2"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\3\26"+
    "\1\27\1\30\1\31\1\26\1\32\1\26\1\33\2\26"+
    "\1\34\3\26\1\35\1\36\1\37\1\2\1\40\1\41"+
    "\1\2\61\0\1\3\102\0\1\42\30\0\2\43\4\0"+
    "\1\43\1\44\47\43\11\0\1\45\62\0\1\46\60\0"+
    "\1\47\1\0\1\50\55\0\1\51\1\0\1\20\62\0"+
    "\1\52\56\0\1\53\56\0\1\54\56\0\1\55\52\0"+
    "\1\56\5\0\21\56\2\0\1\57\25\0\1\56\5\0"+
    "\4\56\1\60\2\56\1\61\11\56\2\0\1\57\1\0"+
    "\1\62\23\0\1\56\5\0\12\56\1\63\6\56\2\0"+
    "\1\57\25\0\1\56\5\0\10\56\1\64\10\56\2\0"+
    "\1\57\25\0\1\56\5\0\5\56\1\65\4\56\1\66"+
    "\6\56\2\0\1\57\25\0\1\56\5\0\13\56\1\67"+
    "\5\56\2\0\1\57\25\0\1\56\5\0\4\56\1\70"+
    "\14\56\2\0\1\57\25\0\1\56\5\0\6\56\1\71"+
    "\5\56\1\72\4\56\2\0\1\57\57\0\1\73\37\0"+
    "\1\74\4\0\1\75\14\0\17\50\1\76\1\50\1\77"+
    "\35\50\22\0\1\100\56\0\1\56\5\0\2\56\1\101"+
    "\16\56\2\0\1\57\25\0\1\56\5\0\17\56\1\102"+
    "\1\56\2\0\1\57\52\0\1\103\31\0\1\56\5\0"+
    "\3\56\1\104\15\56\2\0\1\57\25\0\1\56\5\0"+
    "\13\56\1\105\5\56\2\0\1\57\25\0\1\56\5\0"+
    "\10\56\1\106\5\56\1\107\2\56\2\0\1\57\25\0"+
    "\1\56\5\0\3\56\1\110\15\56\2\0\1\57\25\0"+
    "\1\56\5\0\1\111\20\56\2\0\1\57\25\0\1\56"+
    "\5\0\7\56\1\112\11\56\2\0\1\57\1\0\1\113"+
    "\23\0\1\56\5\0\7\56\1\114\11\56\2\0\1\57"+
    "\1\0\1\115\41\0\1\116\5\0\1\117\10\0\17\50"+
    "\1\76\1\50\1\120\54\50\1\121\1\50\1\77\35\50"+
    "\22\0\1\56\5\0\17\56\1\122\1\56\2\0\1\57"+
    "\25\0\1\56\5\0\3\56\1\123\15\56\2\0\1\57"+
    "\25\0\1\56\5\0\1\124\20\56\2\0\1\57\25\0"+
    "\1\56\5\0\7\56\1\125\11\56\2\0\1\57\1\0"+
    "\1\126\23\0\1\56\5\0\3\56\1\127\15\56\2\0"+
    "\1\57\25\0\1\56\5\0\10\56\1\130\10\56\2\0"+
    "\1\57\43\0\1\131\40\0\1\56\5\0\16\56\1\132"+
    "\2\56\2\0\1\57\51\0\1\133\47\0\1\126\15\0"+
    "\1\126\1\0\17\134\1\135\1\134\1\136\35\134\17\137"+
    "\1\140\1\137\1\141\35\137\22\0\1\56\5\0\1\142"+
    "\20\56\2\0\1\57\25\0\1\56\5\0\4\56\1\143"+
    "\14\56\2\0\1\57\25\0\1\56\5\0\16\56\1\144"+
    "\2\56\2\0\1\57\25\0\1\56\5\0\15\56\1\145"+
    "\3\56\2\0\1\57\2\0\1\146\45\0\1\146\10\0"+
    "\1\146\22\0\1\56\5\0\4\56\1\147\14\56\2\0"+
    "\1\57\37\0\1\150\44\0\1\56\5\0\4\56\1\151"+
    "\14\56\2\0\1\57\37\0\1\152\22\0\21\134\1\136"+
    "\35\134\21\141\1\153\35\141\17\134\1\154\1\134\1\136"+
    "\35\134\17\137\1\140\37\137\22\0\1\56\5\0\14\56"+
    "\1\155\4\56\2\0\1\57\25\0\1\56\5\0\2\56"+
    "\1\156\16\56\2\0\1\57\25\0\1\56\5\0\16\56"+
    "\1\157\2\56\2\0\1\57\51\0\1\160\10\0\17\141"+
    "\1\161\1\141\1\153\35\141\21\161\1\162\54\161\1\163"+
    "\1\161\1\162\35\161";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3290];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\1\1\3\11\1\1\1\11"+
    "\1\1\1\11\2\1\1\11\13\1\2\11\2\1\1\11"+
    "\1\0\1\1\3\11\2\0\4\11\1\1\1\0\2\1"+
    "\1\0\10\1\2\11\3\0\3\1\1\11\7\1\1\0"+
    "\1\1\2\0\1\11\1\0\5\1\1\0\2\1\1\0"+
    "\1\1\2\0\1\1\4\0\4\1\1\0\1\1\1\11"+
    "\1\1\1\11\1\0\4\1\1\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    int RANGO_ENTERO = Integer.MAX_VALUE;
    float RANGO_FLOAT = Float.MAX_VALUE;
    int RANGO_STRING = 30;
    private Symbol symbol(int type) {
          System.out.println("[LEX] TOKEN < " + Simbolos.terminalNames[type] + " > : " + yytext());
          return new Symbol(type, yyline, yycolumn, yytext());
    }
    private Symbol symbol(int type, Object value) {
          return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                /*return symbol(Simbolos.EOF);*/ throw new Error("END OF FILE");
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error Léxico: --> " + yytext() + " <-- Linea " + (yyline+1) + " Columna " + yycolumn);
            throw new Error("Error léxico");
            }
            // fall through
          case 43: break;
          case 2:
            { /* do nothing */
            }
            // fall through
          case 44: break;
          case 3:
            { return symbol(Simbolos.OP_NOT);
            }
            // fall through
          case 45: break;
          case 4:
            { return symbol(Simbolos.OP_MODULE);
            }
            // fall through
          case 46: break;
          case 5:
            { return symbol(Simbolos.PAREN_OPEN);
            }
            // fall through
          case 47: break;
          case 6:
            { return symbol(Simbolos.PAREN_CLOSE);
            }
            // fall through
          case 48: break;
          case 7:
            { return symbol(Simbolos.OP_MULTI);
            }
            // fall through
          case 49: break;
          case 8:
            { return symbol(Simbolos.OP_PLUS);
            }
            // fall through
          case 50: break;
          case 9:
            { return symbol(Simbolos.COMA);
            }
            // fall through
          case 51: break;
          case 10:
            { return symbol(Simbolos.OP_MINUS);
            }
            // fall through
          case 52: break;
          case 11:
            { return symbol(Simbolos.OP_DIVISION);
            }
            // fall through
          case 53: break;
          case 12:
            { Integer constInt = Integer.parseInt(yytext());

                                    if(Math.abs(constInt) <= RANGO_ENTERO ){
                                          return symbol(Simbolos.CONSTANTE_ENTERA);
                                    }                                          
                                    else
                                          throw new Error("La constante [" + yytext() + "] esta fuera del limite de los enteros.");
            }
            // fall through
          case 54: break;
          case 13:
            { return symbol(Simbolos.OP_TYPE);
            }
            // fall through
          case 55: break;
          case 14:
            { return symbol(Simbolos.PUNTO_COMA);
            }
            // fall through
          case 56: break;
          case 15:
            { return symbol(Simbolos.OP_LT);
            }
            // fall through
          case 57: break;
          case 16:
            { return symbol(Simbolos.OP_GT);
            }
            // fall through
          case 58: break;
          case 17:
            { return symbol(Simbolos.CORCHETE_OPEN);
            }
            // fall through
          case 59: break;
          case 18:
            { return symbol(Simbolos.CORCHETE_CLOSE);
            }
            // fall through
          case 60: break;
          case 19:
            { return symbol(Simbolos.OP_NE);
            }
            // fall through
          case 61: break;
          case 20:
            { String constString = new String(yytext());
                                    if (constString.length() <= RANGO_STRING)
                                          return symbol(Simbolos.STRING); 
                                    else 
                                          throw new Error("La constante [" + yytext() + "] excede el largo permitido para un string.");
            }
            // fall through
          case 62: break;
          case 21:
            { return symbol(Simbolos.OP_AND);
            }
            // fall through
          case 63: break;
          case 22:
            { return symbol(Simbolos.OP_INCREMENT);
            }
            // fall through
          case 64: break;
          case 23:
            { return symbol(Simbolos.OP_DECREMENT);
            }
            // fall through
          case 65: break;
          case 24:
            { return symbol(Simbolos.OP_ASIG);
            }
            // fall through
          case 66: break;
          case 25:
            { return symbol(Simbolos.OP_LTE);
            }
            // fall through
          case 67: break;
          case 26:
            { return symbol(Simbolos.OP_EQ);
            }
            // fall through
          case 68: break;
          case 27:
            { return symbol(Simbolos.OP_GTE);
            }
            // fall through
          case 69: break;
          case 28:
            { return symbol(Simbolos.IDENTIFICADOR);
            }
            // fall through
          case 70: break;
          case 29:
            { return symbol(Simbolos.IF);
            }
            // fall through
          case 71: break;
          case 30:
            { return symbol(Simbolos.OP_OR);
            }
            // fall through
          case 72: break;
          case 31:
            { Double constFloat = Double.parseDouble(yytext());
                                    if (Math.abs(constFloat) <= RANGO_FLOAT)
                                          return symbol(Simbolos.CONSTANTE_FLOAT);
                                    else
                                          throw new Error("La constante [" + yytext() + "] esta fuera del limite de los flotantes.");
            }
            // fall through
          case 73: break;
          case 32:
            { return symbol(Simbolos.DIV);
            }
            // fall through
          case 74: break;
          case 33:
            { return symbol(Simbolos.INTEGER);
            }
            // fall through
          case 75: break;
          case 34:
            { return symbol(Simbolos.MOD);
            }
            // fall through
          case 76: break;
          case 35:
            { return symbol(Simbolos.COMMENT);
            }
            // fall through
          case 77: break;
          case 36:
            { return symbol(Simbolos.READ);
            }
            // fall through
          case 78: break;
          case 37:
            { return symbol(Simbolos.FLOAT);
            }
            // fall through
          case 79: break;
          case 38:
            { return symbol(Simbolos.WHILE);
            }
            // fall through
          case 80: break;
          case 39:
            { return symbol(Simbolos.WRITE);
            }
            // fall through
          case 81: break;
          case 40:
            { return symbol(Simbolos.DECVAR);
            }
            // fall through
          case 82: break;
          case 41:
            { return symbol(Simbolos.ENDDEC);
            }
            // fall through
          case 83: break;
          case 42:
            { return symbol(Simbolos.INLIST);
            }
            // fall through
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
