// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/jflex/lexer.jflex

package Analizadores;
import java_cup.runtime.*;

/* Directivas */

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\1\7\1\10\2\0\1\11\1\12\3\0\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\10\23\2\0"+
    "\1\24\1\25\1\26\2\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\2\40\1\41\1\40"+
    "\1\42\1\43\2\40\1\44\1\40\1\45\1\40\1\46"+
    "\1\47\1\50\2\40\4\0\1\51\1\0\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\2\63"+
    "\1\64\1\63\1\65\1\66\2\63\1\67\1\63\1\70"+
    "\1\63\1\71\1\72\1\73\2\63\1\0\1\74\10\0"+
    "\1\3\252\0\2\75\u01f6\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\2\11\1\12\1\13\1\14\6\15"+
    "\1\16\6\15\2\1\1\17\1\0\1\20\1\21\1\0"+
    "\1\22\1\23\1\16\1\0\1\11\2\16\1\11\1\24"+
    "\1\25\1\26\1\16\10\15\1\27\1\15\1\27\5\15"+
    "\1\30\1\27\3\0\1\16\1\31\2\32\1\11\1\33"+
    "\1\16\1\0\6\33\1\0\1\33\3\0\1\34\1\35"+
    "\2\16\6\33\1\0\1\33\2\0\1\34\1\33\1\16"+
    "\3\33\1\36\1\33\2\37\2\40\1\0\1\33\1\16"+
    "\1\33\1\41\2\33\2\0\1\42\1\43\2\44\1\16"+
    "\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\76\0\174\0\272\0\370\0\76\0\u0136"+
    "\0\u0174\0\u01b2\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326"+
    "\0\u0364\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0174"+
    "\0\u0516\0\u0554\0\u0592\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8"+
    "\0\76\0\370\0\370\0\76\0\u0706\0\76\0\76\0\u0744"+
    "\0\u0782\0\u07c0\0\u07fe\0\u083c\0\u087a\0\76\0\76\0\76"+
    "\0\u08b8\0\u08f6\0\u08b8\0\u0934\0\u0972\0\u09b0\0\u09ee\0\u0a2c"+
    "\0\u0a6a\0\u08f6\0\u0aa8\0\u08b8\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0"+
    "\0\u0bde\0\76\0\76\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6\0\u0782"+
    "\0\u07fe\0\u083c\0\u0d14\0\u0d52\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a"+
    "\0\u0e88\0\u0ec6\0\u0f04\0\u0f42\0\u0f80\0\u0fbe\0\u0ffc\0\u103a"+
    "\0\u1078\0\u0174\0\u07c0\0\u10b6\0\u10f4\0\u1132\0\u1170\0\u11ae"+
    "\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322\0\u1360\0\76"+
    "\0\u139e\0\u13dc\0\u141a\0\u1458\0\u1496\0\u0d52\0\u14d4\0\u0d52"+
    "\0\76\0\u0d52\0\76\0\u1512\0\u1550\0\u158e\0\u15cc\0\u0d52"+
    "\0\u160a\0\u1648\0\u1686\0\u16c4\0\u0d52\0\76\0\u0d52\0\76"+
    "\0\u1702\0\u0174";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\3\1\4\1\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\2\1\13\1\2\1\14"+
    "\1\15\2\16\1\17\1\20\1\21\3\22\1\23\1\24"+
    "\1\25\2\22\1\26\7\22\1\27\1\22\1\30\3\31"+
    "\1\32\1\33\1\34\2\31\1\35\7\31\1\36\1\31"+
    "\1\37\1\40\100\0\1\3\120\0\1\41\50\0\2\42"+
    "\4\0\2\42\1\43\65\42\12\0\1\44\71\0\1\45"+
    "\4\0\1\30\4\0\4\30\3\0\45\30\16\0\1\46"+
    "\77\0\1\47\65\0\1\45\4\0\1\50\4\0\4\30"+
    "\3\0\45\30\10\0\1\45\4\0\1\30\3\0\1\51"+
    "\1\30\3\52\3\0\1\30\1\53\17\30\1\54\2\30"+
    "\1\53\17\30\1\54\10\0\1\45\4\0\1\30\3\0"+
    "\1\51\1\30\3\55\3\0\45\30\27\0\1\56\75\0"+
    "\1\57\75\0\1\60\56\0\1\45\4\0\1\30\4\0"+
    "\1\30\3\61\3\0\22\62\1\30\22\63\10\0\1\45"+
    "\4\0\1\30\4\0\1\30\3\61\3\0\4\62\1\64"+
    "\15\62\1\30\4\63\1\65\15\63\10\0\1\45\4\0"+
    "\1\30\4\0\1\30\3\61\3\0\13\62\1\66\6\62"+
    "\1\30\13\63\1\67\6\63\10\0\1\45\4\0\1\30"+
    "\4\0\1\30\3\61\3\0\12\62\1\70\7\62\1\30"+
    "\12\63\1\71\7\63\10\0\1\45\4\0\1\30\4\0"+
    "\1\30\3\61\3\0\5\62\1\72\5\62\1\73\6\62"+
    "\1\30\5\63\1\74\5\63\1\75\6\63\10\0\1\45"+
    "\4\0\1\30\4\0\1\30\3\61\3\0\7\62\1\76"+
    "\5\62\1\77\4\62\1\30\7\63\1\100\5\63\1\101"+
    "\4\63\10\0\1\45\4\0\1\30\4\0\1\30\3\61"+
    "\3\0\22\63\1\30\22\63\10\0\1\45\4\0\1\30"+
    "\4\0\1\30\3\61\3\0\4\63\1\65\15\63\1\30"+
    "\4\63\1\65\15\63\10\0\1\45\4\0\1\30\4\0"+
    "\1\30\3\61\3\0\13\63\1\67\6\63\1\30\13\63"+
    "\1\67\6\63\10\0\1\45\4\0\1\30\4\0\1\30"+
    "\3\61\3\0\12\63\1\71\7\63\1\30\12\63\1\71"+
    "\7\63\10\0\1\45\4\0\1\30\4\0\1\30\3\61"+
    "\3\0\5\63\1\74\5\63\1\75\6\63\1\30\5\63"+
    "\1\74\5\63\1\75\6\63\10\0\1\45\4\0\1\30"+
    "\4\0\1\30\3\61\3\0\7\63\1\100\5\63\1\101"+
    "\4\63\1\30\7\63\1\100\5\63\1\101\4\63\76\0"+
    "\1\102\35\0\1\103\5\0\1\104\14\0\1\103\5\0"+
    "\1\104\23\0\1\30\4\0\4\30\3\0\45\30\2\0"+
    "\6\105\1\106\4\105\1\107\4\105\4\50\3\105\45\50"+
    "\2\105\21\0\3\110\60\0\1\45\4\0\1\30\3\0"+
    "\1\51\1\30\3\52\3\0\45\30\10\0\1\45\4\0"+
    "\1\30\4\0\1\30\2\111\1\30\3\0\45\30\10\0"+
    "\1\45\4\0\1\30\4\0\1\30\3\112\3\0\6\112"+
    "\15\30\6\112\14\30\10\0\1\45\4\0\1\30\3\0"+
    "\1\51\1\30\3\113\3\0\45\30\10\0\1\45\4\0"+
    "\1\30\4\0\1\30\3\114\3\0\22\114\1\115\22\114"+
    "\10\0\1\116\4\0\1\30\4\0\1\30\3\117\3\0"+
    "\22\114\1\115\22\114\10\0\1\116\4\0\1\30\4\0"+
    "\1\30\3\117\3\0\2\114\1\120\17\114\1\115\2\114"+
    "\1\120\17\114\10\0\1\45\4\0\1\30\4\0\1\30"+
    "\3\114\3\0\2\114\1\120\17\114\1\115\2\114\1\120"+
    "\17\114\10\0\1\116\4\0\1\30\4\0\1\30\3\117"+
    "\3\0\3\114\1\121\16\114\1\115\3\114\1\121\16\114"+
    "\10\0\1\45\4\0\1\30\4\0\1\30\3\114\3\0"+
    "\3\114\1\121\16\114\1\115\3\114\1\121\16\114\10\0"+
    "\1\116\4\0\1\30\4\0\1\30\3\117\3\0\14\114"+
    "\1\122\5\114\1\115\14\114\1\122\5\114\10\0\1\45"+
    "\4\0\1\30\4\0\1\30\3\114\3\0\14\114\1\122"+
    "\5\114\1\115\14\114\1\122\5\114\10\0\1\116\4\0"+
    "\1\30\4\0\1\30\3\117\3\0\16\114\1\123\3\114"+
    "\1\115\16\114\1\123\3\114\10\0\1\45\4\0\1\30"+
    "\4\0\1\30\3\114\3\0\16\114\1\123\3\114\1\115"+
    "\16\114\1\123\3\114\10\0\1\116\4\0\1\30\4\0"+
    "\1\30\3\117\3\0\10\114\1\124\11\114\1\115\10\114"+
    "\1\124\11\114\1\0\1\125\6\0\1\116\4\0\1\30"+
    "\4\0\1\30\3\117\3\0\10\114\1\126\11\114\1\115"+
    "\10\114\1\126\11\114\1\0\1\127\6\0\1\45\4\0"+
    "\1\30\4\0\1\30\3\114\3\0\10\114\1\124\11\114"+
    "\1\115\10\114\1\124\11\114\1\0\1\125\6\0\1\45"+
    "\4\0\1\30\4\0\1\30\3\114\3\0\10\114\1\126"+
    "\11\114\1\115\10\114\1\126\11\114\1\0\1\127\45\0"+
    "\1\130\22\0\1\130\5\0\13\105\1\131\75\105\1\107"+
    "\4\105\4\50\3\105\45\50\10\105\1\106\4\105\1\107"+
    "\4\105\1\132\3\50\3\105\45\50\2\105\6\0\1\45"+
    "\4\0\1\30\3\0\1\51\1\30\3\133\3\0\45\30"+
    "\10\0\1\45\4\0\1\30\4\0\1\30\3\114\3\0"+
    "\22\114\1\134\22\114\10\0\1\45\4\0\1\30\4\0"+
    "\1\30\3\61\3\0\22\61\1\30\22\61\15\0\1\30"+
    "\4\0\1\30\3\135\3\0\45\30\10\0\1\45\4\0"+
    "\1\30\4\0\1\30\3\136\3\0\22\114\1\134\22\114"+
    "\10\0\1\45\4\0\1\30\4\0\1\30\3\114\3\0"+
    "\17\114\1\137\2\114\1\134\17\114\1\137\2\114\10\0"+
    "\1\45\4\0\1\30\4\0\1\30\3\114\3\0\3\114"+
    "\1\140\16\114\1\134\3\114\1\140\16\114\10\0\1\45"+
    "\4\0\1\30\4\0\1\30\3\114\3\0\1\141\21\114"+
    "\1\134\1\141\21\114\10\0\1\45\4\0\1\30\4\0"+
    "\1\30\3\114\3\0\4\114\1\142\15\114\1\134\4\114"+
    "\1\142\15\114\10\0\1\45\4\0\1\30\4\0\1\30"+
    "\3\114\3\0\12\114\1\143\7\114\1\134\12\114\1\143"+
    "\7\114\43\0\1\144\22\0\1\144\17\0\1\45\4\0"+
    "\1\30\4\0\1\30\3\114\3\0\16\114\1\145\3\114"+
    "\1\134\16\114\1\145\3\114\47\0\1\146\22\0\1\146"+
    "\40\0\1\147\22\0\1\147\17\0\13\105\1\131\4\105"+
    "\1\150\55\105\6\0\1\45\4\0\1\30\4\0\1\30"+
    "\3\151\3\0\22\151\1\30\22\151\10\0\1\45\4\0"+
    "\1\30\4\0\1\30\3\152\3\0\45\30\10\0\1\45"+
    "\4\0\1\30\4\0\1\30\3\153\3\0\22\114\1\134"+
    "\22\114\10\0\1\45\4\0\1\30\4\0\1\30\3\114"+
    "\3\0\1\154\21\114\1\134\1\154\21\114\10\0\1\45"+
    "\4\0\1\30\4\0\1\30\3\114\3\0\4\114\1\155"+
    "\15\114\1\134\4\114\1\155\15\114\10\0\1\45\4\0"+
    "\1\30\4\0\1\30\3\114\3\0\16\114\1\156\3\114"+
    "\1\134\16\114\1\156\3\114\10\0\1\45\4\0\1\30"+
    "\4\0\1\30\3\114\3\0\6\114\1\157\13\114\1\134"+
    "\6\114\1\157\13\114\10\0\1\45\4\0\1\30\4\0"+
    "\1\30\3\114\3\0\4\114\1\160\15\114\1\134\4\114"+
    "\1\160\15\114\35\0\1\161\22\0\1\161\25\0\1\45"+
    "\4\0\1\30\4\0\1\30\3\114\3\0\4\114\1\162"+
    "\15\114\1\134\4\114\1\162\15\114\35\0\1\163\22\0"+
    "\1\163\54\0\1\164\22\0\1\164\23\0\1\45\4\0"+
    "\1\30\4\0\1\30\3\165\3\0\22\165\1\134\22\165"+
    "\10\0\1\45\4\0\1\30\4\0\1\30\3\166\3\0"+
    "\45\30\10\0\1\45\4\0\1\30\4\0\1\30\3\114"+
    "\3\0\22\167\1\134\22\114\10\0\1\45\4\0\1\30"+
    "\4\0\1\30\3\114\3\0\15\114\1\170\4\114\1\134"+
    "\15\114\1\170\4\114\10\0\1\45\4\0\1\30\4\0"+
    "\1\30\3\114\3\0\2\114\1\171\17\114\1\134\2\114"+
    "\1\171\17\114\10\0\1\45\4\0\1\30\4\0\1\30"+
    "\3\114\3\0\4\114\1\172\15\114\1\134\4\114\1\172"+
    "\15\114\35\0\1\173\22\0\1\173\25\0\1\45\4\0"+
    "\1\30\4\0\1\30\3\165\3\0\22\165\1\30\22\165"+
    "\10\0\1\174\4\0\1\30\4\0\4\30\3\0\45\30"+
    "\10\0\1\45\4\0\1\30\4\0\1\30\3\114\3\0"+
    "\22\175\1\134\22\114\10\0\1\45\4\0\1\30\1\0"+
    "\1\176\2\0\1\30\3\114\3\0\22\114\1\134\22\114"+
    "\10\0\1\45\4\0\1\30\4\0\1\30\3\114\3\0"+
    "\15\114\1\177\4\114\1\134\15\114\1\177\4\114\46\0"+
    "\1\200\22\0\1\200\21\0\1\30\4\0\4\30\3\0"+
    "\22\201\23\30\10\0\1\45\4\0\1\30\4\0\4\30"+
    "\3\0\22\202\23\30\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5952];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\31\1\1\11\1\0\1\1"+
    "\1\11\1\0\2\11\1\1\1\0\4\1\3\11\21\1"+
    "\2\11\3\0\7\1\1\0\6\1\1\0\1\1\3\0"+
    "\12\1\1\0\1\1\2\0\1\11\10\1\1\11\1\1"+
    "\1\11\1\0\6\1\2\0\1\1\1\11\1\1\1\11"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    int RANGO_ENTERO = 65536;
    double RANGO_FLOAT = 4294967296L;
    private Symbol symbol(int type) {
          System.out.println("[LEX] TOKEN < " + Simbolos.terminalNames[type] + " > : " + yytext());
          return new Symbol(type, yyline, yycolumn, yytext());
    }
    private Symbol symbol(int type, Object value) {
          return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                /*return symbol(Simbolos.EOF);*/ throw new Error("END OF FILE");
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error Léxico: --> " + yytext() + " <-- Linea " + (yyline+1) + " Columna " + yycolumn);
            throw new Error("Error léxico");
            }
            // fall through
          case 37: break;
          case 2:
            { /* do nothing */
            }
            // fall through
          case 38: break;
          case 3:
            { return symbol(Simbolos.OP_NOT);
            }
            // fall through
          case 39: break;
          case 4:
            { return symbol(Simbolos.OP_MODULE);
            }
            // fall through
          case 40: break;
          case 5:
            { return symbol(Simbolos.OP_MULTI);
            }
            // fall through
          case 41: break;
          case 6:
            { return symbol(Simbolos.OP_PLUS);
            }
            // fall through
          case 42: break;
          case 7:
            { return symbol(Simbolos.OP_MINUS);
            }
            // fall through
          case 43: break;
          case 8:
            { return symbol(Simbolos.OP_DIVISION);
            }
            // fall through
          case 44: break;
          case 9:
            { // 2147483647 is the maximum value parseInt() can parse without giving an exception. 
                                    // Here we defined some custom int max value.
                                    Integer constInt = Integer.parseInt(yytext());

                                    if(constInt >= -RANGO_ENTERO && constInt <= RANGO_ENTERO ){
                                          return symbol(Simbolos.CONSTANTE_ENTERA);
                                    }                                          
                                    else
                                          return symbol(Simbolos.NUMBER);
                                          //throw new Error("La constante [" + yytext() + "] esta fuera del limite de los enteros.");
            }
            // fall through
          case 45: break;
          case 10:
            { return symbol(Simbolos.OP_LT);
            }
            // fall through
          case 46: break;
          case 11:
            { return symbol(Simbolos.OP_ASIG);
            }
            // fall through
          case 47: break;
          case 12:
            { return symbol(Simbolos.OP_GT);
            }
            // fall through
          case 48: break;
          case 13:
            { return symbol(Simbolos.WORD);
            }
            // fall through
          case 49: break;
          case 14:
            { return symbol(Simbolos.TEXT);
            }
            // fall through
          case 50: break;
          case 15:
            { return symbol(Simbolos.OP_NE);
            }
            // fall through
          case 51: break;
          case 16:
            { return symbol(Simbolos.STRING);
            }
            // fall through
          case 52: break;
          case 17:
            { return symbol(Simbolos.OP_AND);
            }
            // fall through
          case 53: break;
          case 18:
            { return symbol(Simbolos.OP_INCREMENT);
            }
            // fall through
          case 54: break;
          case 19:
            { return symbol(Simbolos.OP_DECREMENT);
            }
            // fall through
          case 55: break;
          case 20:
            { return symbol(Simbolos.OP_LTE);
            }
            // fall through
          case 56: break;
          case 21:
            { return symbol(Simbolos.OP_EQ);
            }
            // fall through
          case 57: break;
          case 22:
            { return symbol(Simbolos.OP_GTE);
            }
            // fall through
          case 58: break;
          case 23:
            { return symbol(Simbolos.IF);
            }
            // fall through
          case 59: break;
          case 24:
            { return symbol(Simbolos.OP_OR);
            }
            // fall through
          case 60: break;
          case 25:
            { Double constFloat = Double.parseDouble(yytext());
                                    if (constFloat >= -RANGO_FLOAT && constFloat <= RANGO_FLOAT)
                                          return symbol(Simbolos.CONSTANTE_FLOAT);
                                    else
                                          throw new Error("La constante [" + yytext() + "] esta fuera del limite de los flotantes");
            }
            // fall through
          case 61: break;
          case 26:
            { return symbol(Simbolos.CONSTANTES_C);
            }
            // fall through
          case 62: break;
          case 27:
            { return symbol(Simbolos.IDENTIFICADOR);
            }
            // fall through
          case 63: break;
          case 28:
            { return symbol(Simbolos.COMMENT);
            }
            // fall through
          case 64: break;
          case 29:
            { return symbol(Simbolos.COD_POSTAL);
            }
            // fall through
          case 65: break;
          case 30:
            { return symbol(Simbolos.FLOAT);
            }
            // fall through
          case 66: break;
          case 31:
            { return symbol(Simbolos.WHILE);
            }
            // fall through
          case 67: break;
          case 32:
            { return symbol(Simbolos.WRITE);
            }
            // fall through
          case 68: break;
          case 33:
            { return symbol(Simbolos.DECVAR);
            }
            // fall through
          case 69: break;
          case 34:
            { return symbol(Simbolos.PATENTE_MERCOSUR);
            }
            // fall through
          case 70: break;
          case 35:
            { return symbol(Simbolos.ENDDEC);
            }
            // fall through
          case 71: break;
          case 36:
            { return symbol(Simbolos.INTEGER);
            }
            // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
