
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int OP_NE = 26;
  public static final int ENDDEC = 9;
  public static final int INLIST = 12;
  public static final int OP_GT = 18;
  public static final int OP_NOT = 27;
  public static final int OP_AND = 28;
  public static final int OP_MULTI = 24;
  public static final int WRITE = 10;
  public static final int IDENTIFICADOR = 41;
  public static final int CONSTANTE_ENTERA = 2;
  public static final int DIV = 14;
  public static final int IF = 5;
  public static final int PUNTO_COMA = 34;
  public static final int EOF = 0;
  public static final int LLAVE_CLOSE = 40;
  public static final int STRING_TYPE = 17;
  public static final int OP_DIVISION = 25;
  public static final int OP_GTE = 20;
  public static final int error = 1;
  public static final int OP_LT = 19;
  public static final int COMA = 33;
  public static final int OP_OR = 29;
  public static final int MOD = 13;
  public static final int INTEGER_TYPE = 15;
  public static final int OP_MINUS = 23;
  public static final int DECVAR = 8;
  public static final int CORCHETE_CLOSE = 38;
  public static final int ELSE = 6;
  public static final int READ = 11;
  public static final int WHILE = 7;
  public static final int OP_TYPE = 32;
  public static final int OP_EQ = 31;
  public static final int PAREN_CLOSE = 36;
  public static final int LLAVE_OPEN = 39;
  public static final int CONSTANTE_STRING = 4;
  public static final int OP_PLUS = 22;
  public static final int FLOAT_TYPE = 16;
  public static final int OP_LTE = 21;
  public static final int CORCHETE_OPEN = 37;
  public static final int CONSTANTE_FLOAT = 3;
  public static final int OP_ASIG = 30;
  public static final int PAREN_OPEN = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONSTANTE_ENTERA",
  "CONSTANTE_FLOAT",
  "CONSTANTE_STRING",
  "IF",
  "ELSE",
  "WHILE",
  "DECVAR",
  "ENDDEC",
  "WRITE",
  "READ",
  "INLIST",
  "MOD",
  "DIV",
  "INTEGER_TYPE",
  "FLOAT_TYPE",
  "STRING_TYPE",
  "OP_GT",
  "OP_LT",
  "OP_GTE",
  "OP_LTE",
  "OP_PLUS",
  "OP_MINUS",
  "OP_MULTI",
  "OP_DIVISION",
  "OP_NE",
  "OP_NOT",
  "OP_AND",
  "OP_OR",
  "OP_ASIG",
  "OP_EQ",
  "OP_TYPE",
  "COMA",
  "PUNTO_COMA",
  "PAREN_OPEN",
  "PAREN_CLOSE",
  "CORCHETE_OPEN",
  "CORCHETE_CLOSE",
  "LLAVE_OPEN",
  "LLAVE_CLOSE",
  "IDENTIFICADOR"
  };
}

