
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int OP_NE = 25;
  public static final int ENDDEC = 8;
  public static final int INLIST = 13;
  public static final int COMMENT = 39;
  public static final int OP_GT = 14;
  public static final int INTEGER = 9;
  public static final int OP_NOT = 26;
  public static final int OP_AND = 27;
  public static final int OP_MULTI = 20;
  public static final int WRITE = 11;
  public static final int IDENTIFICADOR = 38;
  public static final int OP_INCREMENT = 23;
  public static final int CONSTANTE_ENTERA = 2;
  public static final int IF = 5;
  public static final int PUNTO_COMA = 33;
  public static final int OP_DECREMENT = 24;
  public static final int EOF = 0;
  public static final int OP_DIVISION = 21;
  public static final int OP_GTE = 16;
  public static final int error = 1;
  public static final int OP_LT = 15;
  public static final int COMA = 32;
  public static final int OP_OR = 28;
  public static final int OP_MINUS = 19;
  public static final int DECVAR = 7;
  public static final int CORCHETE_CLOSE = 37;
  public static final int READ = 12;
  public static final int WHILE = 6;
  public static final int FLOAT = 10;
  public static final int OP_MODULE = 22;
  public static final int OP_TYPE = 31;
  public static final int OP_EQ = 30;
  public static final int STRING = 4;
  public static final int PAREN_CLOSE = 35;
  public static final int OP_PLUS = 18;
  public static final int OP_LTE = 17;
  public static final int CORCHETE_OPEN = 36;
  public static final int CONSTANTE_FLOAT = 3;
  public static final int OP_ASIG = 29;
  public static final int PAREN_OPEN = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONSTANTE_ENTERA",
  "CONSTANTE_FLOAT",
  "STRING",
  "IF",
  "WHILE",
  "DECVAR",
  "ENDDEC",
  "INTEGER",
  "FLOAT",
  "WRITE",
  "READ",
  "INLIST",
  "OP_GT",
  "OP_LT",
  "OP_GTE",
  "OP_LTE",
  "OP_PLUS",
  "OP_MINUS",
  "OP_MULTI",
  "OP_DIVISION",
  "OP_MODULE",
  "OP_INCREMENT",
  "OP_DECREMENT",
  "OP_NE",
  "OP_NOT",
  "OP_AND",
  "OP_OR",
  "OP_ASIG",
  "OP_EQ",
  "OP_TYPE",
  "COMA",
  "PUNTO_COMA",
  "PAREN_OPEN",
  "PAREN_CLOSE",
  "CORCHETE_OPEN",
  "CORCHETE_CLOSE",
  "IDENTIFICADOR",
  "COMMENT"
  };
}

